/**
 *
 * $Id$
 */
package ccsM2.validation;

import ccsM2.IComponentElement;
import ccsM2.Role;

/**
 * A sample validator interface for {@link ccsM2.Attachement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttachementValidator {
	boolean validate();

	boolean validateIcomponentelement(IComponentElement value);

	boolean validateRole(Role value);
}
