/**
 *
 * $Id$
 */
package ccsM2.validation;

import ccsM2.Component;
import ccsM2.Connector;
import ccsM2.ILink;
import ccsM2.PortConfiguration;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ccsM2.Configuration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigurationValidator {
	boolean validate();

	boolean validateConnector(EList<Connector> value);

	boolean validateComponent(EList<Component> value);

	boolean validatePortconfiguration(EList<PortConfiguration> value);

	boolean validateIlink(EList<ILink> value);
}
