/**
 *
 * $Id$
 */
package ccsM2.validation;

import ccsM2.Glue;
import ccsM2.Role;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ccsM2.Connector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectorValidator {
	boolean validate();

	boolean validateGlue(Glue value);

	boolean validateRole(EList<Role> value);
}
