/**
 *
 * $Id$
 */
package ccsM2.validation;

import ccsM2.Mode;
import ccsM2.Visibility;

/**
 * A sample validator interface for {@link ccsM2.InterfaceElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterfaceElementValidator {
	boolean validate();

	boolean validateMode(Mode value);

	boolean validateVisibility(Visibility value);

	boolean validateContainedValue(Object value);
}
